services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BD\EzPlatformFileBasedContentType\Platform\SPI\Persistence\ContentTypeHandler:
        decorates: ezpublish.spi.persistence.legacy.content_type.handler.inner
        arguments:
            - '@BD\EzPlatformFileBasedContentType\Platform\SPI\Persistence\ContentTypeHandler.inner'
            -
                17: 'AppBundle\Platform\ContentTypes\FileBasedTestContentType'

